// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitle("RdfProvider.DesignTime")>]
[<assembly: AssemblyProduct("RdfProvider")>]
[<assembly: AssemblyDescription("This library is for the .NET platform implementing RdfProvider.")>]
[<assembly: AssemblyVersion("1.0.0")>]
[<assembly: AssemblyFileVersion("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "RdfProvider.DesignTime"

    [<Literal>]
    let AssemblyProduct = "RdfProvider"

    [<Literal>]
    let AssemblyDescription =
        "This library is for the .NET platform implementing RdfProvider."

    [<Literal>]
    let AssemblyVersion = "1.0.0"

    [<Literal>]
    let AssemblyFileVersion = "1.0.0"
