// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RdfProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("RdfProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing RdfProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RdfProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "RdfProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing RdfProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
